name: CI
on:
  push:
    branches: [work]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.14
      - run: bun install
      - run: bun run qc
      - name: Build Docker images
        run: |
          docker build -t ghcr.io/example/auth services/auth
          docker build -t ghcr.io/example/score services/score
          docker build -t ghcr.io/example/ledger services/ledger
      - name: Push images
        run: |
          echo "$CR_PAT" | docker login ghcr.io -u user --password-stdin
          docker push ghcr.io/example/auth
          docker push ghcr.io/example/score
          docker push ghcr.io/example/ledger
